### ISSUE TITLE
Error when setting `postMessage` origin through broadcast options

### ISSUE THREAD

**Issue by samuelthompson189** [L-Chris/vuex-iframe-sync#2] opened 2018-06-18 01:46 UTC
Hi

My application requires an iframe window which can can navigate between pages. Because the `ObserverIframe` class defaults the origin to `window.location`  as soon as the `src` attribute is updated,  the iframe sync breaks with the following error:
```
DOMException: Failed to execute 'postMessage' on 'Window': Invalid target origin '' in a call to 'postMessage'.
```

 I think it would be a good idea to set the default option to `"*"`, make it configurable, or provide an API to update the origin through some event hook of some kind (if this does not exist already?)

Cheers

**Comment by samuelthompson189** [comment] 2018-06-18 02:05
After re-looking through the docs I see that you can define the origin via the broadcast options. However there looks to be a bug when I import the library like so:
```
import { broadcast } from 'vuex-iframe-sync'
// ...
plugins: [
  broadcast([
    { id: "my-id", origin: "*" }
  ])
]
```

I get the error `vuex-iframe-sync.es.js?6fbb:1 Uncaught TypeError: t.ids.split is not a function` which seems to be related to the bundled version as the library works correctly if imported like so:
```
import { broadcast } from 'vuex-iframe-sync/src/index`
```

**Comment by L-Chris** [comment] 2018-07-04 12:50
@samuelthompson189 
Sorry, I can't reproduce the problem. It goes fine in my case.
Thanks for your advice, it will be in next release.

**Closed** 2018-07-18 13:30 UTC
Labels: bug, enhancement
